
import React from 'react';
import { ShieldCheck, Download, RefreshCw, AlertTriangle } from 'lucide-react';
import { LogEntry } from '../types';

interface Props {
  logs: LogEntry[];
  duration: string;
  onReset: () => void;
}

export const ComplianceModal: React.FC<Props> = ({ logs, duration, onReset }) => {
  const errors = logs.filter(l => l.type === 'ERROR').length;
  const complianceScore = Math.max(0, 100 - (errors * 15));

  const handleDownload = () => {
    const sessionId = Math.random().toString(36).substr(2, 9).toUpperCase();
    const date = new Date().toLocaleString();
    
    const reportContent = `
ENTROPYGUARD V2.0 - SESSION SUMMARY
===================================
Session ID:       ${sessionId}
Date:             ${date}
Duration:         ${duration}
Compliance Score: ${complianceScore}%
Critical Errors:  ${errors}

-----------------------------------
EVENT LOGS
-----------------------------------
${logs.map(l => `[${l.timestamp}] [${l.type}] ${l.message}`).join('\n')}

-----------------------------------
Generated by EntropyGuard AI
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `EntropyGuard_Report_${sessionId}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };
  
  return (
    <div className="fixed inset-0 z-50 bg-[#111318]/90 backdrop-blur-md flex flex-col items-center justify-center p-6 animate-in zoom-in-95">
      <div className="w-full max-w-lg bg-[#1E2229] border border-[#444746] rounded-[2rem] p-8 shadow-2xl relative overflow-hidden">
        
        {/* Decorative Background */}
        <div className="absolute top-0 left-0 w-full h-2 bg-gradient-to-r from-[#6DD58C] via-[#A8C7FA] to-[#6DD58C]" />

        <div className="flex flex-col items-center text-center mb-8">
            <div className="w-20 h-20 bg-[#003817] rounded-full flex items-center justify-center mb-4 border-4 border-[#1E2229] shadow-lg">
                <ShieldCheck size={40} className="text-[#6DD58C]" />
            </div>
            <h2 className="text-3xl font-bold text-[#E3E3E3] font-[Google Sans]">Session Summary</h2>
            <p className="text-[#C4C7C5] mt-2">Compliance Certificate Ready</p>
        </div>

        <div className="grid grid-cols-2 gap-4 mb-8">
            <div className="bg-[#111318] p-4 rounded-2xl border border-[#2B2F36]">
                <p className="text-xs text-[#8E918F] uppercase">Duration</p>
                <p className="text-xl font-mono text-[#E3E3E3]">{duration}</p>
            </div>
            <div className="bg-[#111318] p-4 rounded-2xl border border-[#2B2F36]">
                <p className="text-xs text-[#8E918F] uppercase">Critical Errors</p>
                <p className={`text-xl font-mono ${errors > 0 ? 'text-[#FFB4AB]' : 'text-[#6DD58C]'}`}>{errors}</p>
            </div>
            <div className="col-span-2 bg-[#111318] p-4 rounded-2xl border border-[#2B2F36] flex items-center justify-between">
                <div>
                    <p className="text-xs text-[#8E918F] uppercase">Compliance Score</p>
                    <p className={`text-2xl font-bold ${complianceScore > 80 ? 'text-[#6DD58C]' : 'text-[#FFB4AB]'}`}>{complianceScore}%</p>
                </div>
                {complianceScore < 100 && <AlertTriangle className="text-[#FFB4AB]" />}
            </div>
        </div>

        <div className="flex gap-4">
            <button onClick={onReset} className="flex-1 py-3 bg-[#2B2F36] hover:bg-[#3F444D] text-[#E3E3E3] rounded-full font-bold transition-colors flex items-center justify-center gap-2">
                <RefreshCw size={18} /> New Task
            </button>
            <button onClick={handleDownload} className="flex-1 py-3 bg-[#A8C7FA] hover:bg-[#D3E3FD] text-[#062E6F] rounded-full font-bold transition-colors flex items-center justify-center gap-2 shadow-lg">
                <Download size={18} /> Download Report
            </button>
        </div>

      </div>
    </div>
  );
};
